version: '2.1'

services:
  terraform:
    image: "${DOCKER_HUB:-}${DOCKER_IMAGE:-terraform-aws-skeleton}:${DOCKER_IMAGE_TAG:-latest}"
    build:
      context: .
      args:
        TERRAFORM_IMAGE: "${TERRAFORM_IMAGE:-hashicorp/terraform}"
        TERRAFORM_IMAGE_TAG: "${TERRAFORM_IMAGE_TAG:-latest}"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION:-eu-west-2}"
      TF_VAR_environment: "${ENVIRONMENT:-test}"

  terraform-init:
    extends:
      service: terraform
    entrypoint: []
    command: |
      terraform init
        -backend-config="bucket=${TERRAFORM_BACKEND_S3_BUCKET_NAME}"

  aws-cli:
    image: "${AWS_CLI_IMAGE:-mikesir87/aws-cli}:${AWS_CLI_IMAGE_TAG:-latest}"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION:-eu-west-2}"